# Generated by Django 4.1.4 on 2022-12-29 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
